INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('6d4b30cd-775b-4a4c-9365-85b21066130d', 'GraphQL getting started', 'In this course we take a look at a new data query language and runtime called GraphQL', 'In this course we take a look at a new data query language and runtime called GraphQL. GraphQL was designed and built at Facebook to help product developers request and receive the data they need for their mobile and web applications. GraphQL sits on top of your application’s data access layer, providing clients with the ability to explicitly specify their data requirements, and the guarantee that this data won’t change.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('a4d145c8-df92-4f13-aca0-12fb0a257df2', 'Data Science', 'This Specialization covers the concepts and tools you will need throughout the entire data science pipeline', 'This Specialization covers the concepts and tools you will need throughout the entire data science pipeline, from asking the right kinds of questions to making inferences and publishing results. In the final Capstone Project, you’ll apply the skills learned by building a data product using real-world data. At completion, students will have a portfolio demonstrating their mastery of the material.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('ae0da6e8-7be0-40bd-89d7-61b87764cb5b', 'Fundamentals of computing', 'This Specialization covers much of the material that first-year Computer Science students take at Rice University', 'This Specialization covers much of the material that first-year Computer Science students take at Rice University. Students learn sophisticated programming skills in Python from the ground up and apply these skills in building more than 20 fun projects. The Specialization concludes with a Capstone exam that allows the students to demonstrate the range of knowledge that they have acquired in the Specialization.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('4b359b65-d51f-4c32-bcfc-fb8bcf8a7d17', 'Search Engine Optimization', 'This Specialization will teach you to optimize website content for the best possible search engine ranking', 'This Specialization will teach you to optimize website content for the best possible search engine ranking. You will learn the theory behind Google search and other search engine algorithms; you will also build practical, real-world skills that you can apply to a career in internet marketing or online content development, including on-page and off-page optimization, optimizing for local and international audiences, conducting search-focused website audits, and aligning SEO with overall business strategies. Each course is intended to build on the skills from the previous course, thus we recommend you take the courses in the order they are listed. The Specialization culminates in a hands-on Capstone Project, in which you will apply your skills to a comprehensive SEO consulting task.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('c9b0f9e3-eb63-4d3e-8da5-3e978d99c63e', 'Creative writing', 'This Specialization covers elements of three major creative writing genres: short story, narrative essay, and memoir', 'This Specialization covers elements of three major creative writing genres: short story, narrative essay, and memoir. You will master the techniques that good writers use to compose a bracing story, populated with memorable characters in an interesting setting, written in a fresh descriptive style. You will analyze and constructively evaluate peer writing. In the Capstone, you will draft, rewrite, and complete a substantial original story in the genre of your choosing.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('a598427a-44c6-4aab-bb95-75a77a65d06f', 'Statistics with R', 'In this Specialization, you will learn to analyze and visualize data in R and created reproducible data analysis reports', 'In this Specialization, you will learn to analyze and visualize data in R and created reproducible data analysis reports, demonstrate a conceptual understanding of the unified nature of statistical inference, perform frequentist and Bayesian statistical inference and modeling to understand natural phenomena and make data-based decisions, communicate statistical results correctly, effectively, and in context without relying on statistical jargon, critique data-based claims and evaluated data-based decisions, and wrangle and visualize data with R packages for data analysis.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('015e57f6-30e8-4213-ba58-4301809f1ad1', 'Interaction Design', 'You will learn how to design technologies that bring people joy, rather than frustration', 'You will learn how to design technologies that bring people joy, rather than frustration. You will learn how to generate design ideas, techniques for quickly prototyping them, and how to use prototypes to get feedback from other stakeholders like your teammates, clients, and users. You will also learn principles of visual design, perception, and cognition that inform effective interaction design.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('1bfa3737-66c2-4426-a57e-ed6b311c4416', 'Become a journalist', 'This Specialization will develop and enhance your understanding of the global field of journalism', 'This Specialization will develop and enhance your understanding of the global field of journalism. You will learn best practices and ethical standards for newsgathering processes and compiling a news report through hands-on projects, peer-to-peer feedback, and issue exploration. You will also study journalisms impact on societal issues and trends, plus explore career opportunities in newspapers, magazine, social media, Internet multimedia, television, radio, corporate and community journalism. The final Capstone project will guide you through the journalistic portfolio process, where you will conceptualize, report and complete a professional-quality news report.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('8304ee81-abbf-4566-9f13-bca1ded0d4f3', 'Virtual Teacher', 'This series of courses provides best practices for online instruction, student engagement and virtual community building', 'This series of courses provides best practices for online instruction, student engagement and virtual community building; effective uses of asynchronous and synchronous technologies, social media and other emerging technologies; and data analysis techniques and student performance measurements to individualize instruction in an online or blended environment. The courses in this Specialization may be taken in any order. Each course can be taken independently. The Specialization concludes with a final project that will give you the opportunity to integrate and apply the skills you have gained throughout the courses.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('75e54bc1-dd9a-4b7b-a9e9-f56ebac91a72', 'Introduction to Psychology', 'This course will highlight the most interesting experiments within the field of psychology', 'This course will highlight the most interesting experiments within the field of psychology, discussing the implications of those studies for our understanding of the human mind and human behavior.  We will explore the brain and some of the cognitive abilities it supports like memory, learning, attention, perception and consciousness.  We will examine human development - both in terms of growing up and growing old - and will discuss the manner in which the behavior of others affect our own thoughts and behavior.  Finally we will discuss various forms of mental illness and the treatments that are used to help those who suffer from them.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('bdaada5c-6548-4496-919a-79bec9225244', 'Game Theory', 'Popularized by movies such as "A Beautiful Mind," game theory is the mathematical modeling of strategic interaction among rational (and irrational) agents', 'Popularized by movies such as "A Beautiful Mind," game theory is the mathematical modeling of strategic interaction among rational (and irrational) agents. Beyond what we call games in common language, such as chess, poker, soccer, etc., it includes the modeling of conflict among nations, political campaigns, competition among firms, and trading behavior in markets such as the NYSE. How could you begin to model keyword auctions, and peer to peer file-sharing networks, without accounting for the incentives of the people using them? The course will provide the basics: representing games and strategies, the extensive form (which computer scientists call game trees), Bayesian games (modeling things like auctions), repeated and stochastic games, and more. We will include a variety of examples including classic games and a few applications.', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');

INSERT INTO course (id, title, pitch, description, member_limit, created_by, status) VALUES ('9b4147d1-bdc5-4bd9-af06-52d4346fab93', 'Buddhism and Modern Psychology', 'The Dalai Lama has said that Buddhism and science are deeply compatible and has encouraged Western scholars to critically examine both the meditative practice and Buddhist ideas about the human mind', 'The Dalai Lama has said that Buddhism and science are deeply compatible and has encouraged Western scholars to critically examine both the meditative practice and Buddhist ideas about the human mind. A number of scientists and philosophers have taken up this challenge. There have been brain scans of meditators and philosophical examinations of Buddhist doctrines. There have even been discussions of Darwin and the Buddha: Do early Buddhist pitch, descriptions of the mind, and of the human condition, make particular sense in light of evolutionary psychology?', 5, '588034cb-4c84-4f36-abcf-fa511aba0de3', 'active');
